import React from 'react';
 import styles from "./Layout.module.css";
 import Head from 'next/head';
 import Image from 'next/image';

const Layout = ({children, title="World Stats"}) => {
  return (
<div className={styles.container}>
      <Head>
        <title>{title} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <img src="./logo.webp" alt="World Icon" width="70px"/>
      </header>
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>
        Oscar Sánchez-Marín Baquero- UPGRADE HUB
      </footer>
     
    </div>
  )
}

export default Layout